services:
  mysql:
    image: mysql:8.0
    container_name: push-mysql
    environment:
      MYSQL_ROOT_PASSWORD: test
      MYSQL_DATABASE: test-local_db
      MYSQL_USER: test
      MYSQL_PASSWORD: test
      TZ: 'Asia/Tokyo'
    command: mysqld --default-authentication-plugin=mysql_native_password
    volumes:
      - ./data:/var/lib/mysql
    ports:
      - "3406:3306"
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u$$MYSQL_USER -p$$MYSQL_PASSWORD

  backend:
    build: ./backend
    container_name: push-backend
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend:/code
      - ./backend/firebase-adminsdk.json:/code/firebase-adminsdk.json
    ports:
      - "8000:8000"
    depends_on:
      mysql:
        condition: service_healthy

  frontend:
    build: ./frontend
    container_name: push-frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    environment:
      - NODE_ENV=development
    command: "npm run dev -- --hostname 0.0.0.0"